name: Build pdf

on:
  push:
    branches:
      - '**'
    paths:
      - '*/scripts/statement.sh'
      - '*/statement/*.jpg'
      - '*/statement/DISABLE_AUTO_BUILD'
      - '*/statement/index.md'
      - '*/problem.json'
      - '*/subtasks.json'
      - 'appendix.tex'
      - 'cover.tex'
      - 'template.tex'
  workflow_dispatch:

jobs:
  run:
    if: ${{ github.repository != 'tw20000807/tps-starter' }}
    uses: tw20000807/tps-actions/.github/workflows/build-pdf.yml@main
