name: New problem

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Problem name? (Only A-Z or a-z allowed; use spaces to separate multiple problems)'
        required: true

jobs:
  run:
    uses: tw20000807/tps-actions/.github/workflows/new-problem.yml@main
    with:
      name: ${{ github.event.inputs.name }}
