name: New problem

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'problem name? (only allow a-z and A-Z)'
        required: true

jobs:
  run:
    uses: tw20000807/tps-actions/.github/workflows/new-problem.yml@main
    with:
      name: ${{ github.event.inputs.name }}
